# manage_issues.ps1

# 1. Close implemented issues
$implemented = @(2, 3, 4, 5, 6, 9, 10, 11, 12, 13)
Write-Host "Closing implemented issues..."
foreach ($num in $implemented) {
    gh issue close $num --comment "Implemented in the latest platform hardening turn."
}

# 2. Create 40 NEW critical issues
$newIssues = @(
    @{title="[Security] Audit for SQL Injection in Dynamic Filters"; body="## [PROBLEM]`nCurrently, some database queries might use raw SQL fragments. `n`n## [REQUIRED FIX]`n- Audit all files in `api-server/src/routes` and `lib/db/src/schema`.`n- Ensure all dynamic filters use Drizzle's `eq`, `and`, `or` helpers instead of raw template strings.`n- Verify that user-supplied input is never directly concatenated into SQL."; label="critical,security"},
    @{title="[Security] Implement Strict Content Security Policy (CSP)"; body="## [PROBLEM]`nThe application lacks a strict CSP, making it vulnerable to XSS and data injection.`n`n## [REQUIRED FIX]`n- Add `helmet` middleware to `app.ts`.`n- Configure a strict CSP that only allows trusted sources for scripts, styles, and images.`n- Specifically, ensure `tesseract.js` worker scripts are handled correctly."; label="critical,security"},
    @{title="[Security] Sanitize AI-Generated Content Before Rendering"; body="## [PROBLEM]`nAI-generated content (resumes/cover letters) based on potentially malicious job descriptions could contain injection attacks.`n`n## [REQUIRED FIX]`n- Implement a sanitization layer (e.g., `dompurify` or `isomorphic-dompurify`) before displaying AI output in the frontend.`n- Specifically target the `AnalysisDetail` component."; label="critical,security"},
    @{title="[Security] Rate Limit per Authenticated User ID"; body="## [PROBLEM]`nExisting rate limits are IP-based, which can be bypassed via proxies. `n`n## [REQUIRED FIX]`n- Update `rate-limiter.ts` to use `req.user.id` for limiting authenticated requests.`n- Keep IP-based limits as a fallback for unauthenticated routes."; label="critical,security"},
    @{title="[Security] Audit and Enforce JWT Signing Algorithm (HS256)"; body="## [PROBLEM]`nJWT verification might be susceptible to 'algorithm: none' attacks if not strictly configured.`n`n## [REQUIRED FIX]`n- In `lib/auth.ts`, explicitly pass `{ algorithms: ['HS256'] }` to the `jwt.verify` call.`n- Ensure any token with a different algorithm is rejected immediately."; label="critical,security"},
    @{title="[Security] Secure Cookie Flag Enforcement"; body="## [PROBLEM]`nSession/Auth cookies might lack essential security flags.`n`n## [REQUIRED FIX]`n- Update `cookie-parser` and `express-session` config in `app.ts`.`n- Set `httpOnly: true`, `secure: true`, and `sameSite: 'strict'` for all auth-related cookies."; label="critical,security"},
    @{title="[Reliability] Database Deadlock Prevention on Concurrent Analyses"; body="## [PROBLEM]`nHigh concurrency during resume analysis could lead to database deadlocks when updating usage counts and analysis records.`n`n## [REQUIRED FIX]`n- Audit the transaction block in `api-server/src/routes/analyses.ts`.`n- Ensure consistent lock ordering across all routes that update user usage."; label="critical,reliability"},
    @{title="[Reliability] AI Response Schema Validation (Zod)"; body="## [PROBLEM]`nIf the LLM returns malformed JSON, the application crashes during parsing.`n`n## [REQUIRED FIX]`n- Implement a robust Zod schema for the AI's JSON output in `lib/ai.ts`.`n- Use `safeParse` and implement a fallback mechanism (retry or friendly error) if validation fails."; label="critical,reliability"},
    @{title="[Reliability] Circuit Breaker for AI API Outages"; body="## [PROBLEM]`nExternal AI API outages cause 500 errors and a poor user experience.`n`n## [REQUIRED FIX]`n- Implement a circuit breaker pattern in `lib/ai.ts`.`n- If the API fails consecutively, return a custom error that the frontend can display as an 'AI at capacity' message."; label="critical,reliability"},
    @{title="[Reliability] Automated DB Backups and Recovery Plan"; body="## [PROBLEM]`nThere is no automated backup strategy or disaster recovery plan for the PostgreSQL database.`n`n## [REQUIRED FIX]`n- Create a GitHub Action to perform daily `pg_dump` backups.`n- Store backups in a secure, off-site location (e.g., S3).`n- Document the Point-In-Time-Recovery (PITR) process."; label="critical,reliability"},
    @{title="[Performance] Redis Caching for Scraped Job Descriptions"; body="## [PROBLEM]`nRepeatedly scraping the same job URLs is inefficient and increases latency.`n`n## [REQUIRED FIX]`n- Integrate Redis for caching.`n- Cache scraped job text for 24 hours keyed by the normalized URL.`n- Implement a 'force-refresh' option for the scraper."; label="critical,performance"},
    @{title="[Performance] Database Index Optimization for History Search"; body="## [PROBLEM]`nAs the `analyses` table grows, dashboard loading and history searches will become slow.`n`n## [REQUIRED FIX]`n- Add composite indexes on `(user_id, created_at)` in the `analyses` and `resumes` tables.`n- Audit all query plans to ensure indexes are being utilized."; label="critical,performance"},
    @{title="[Performance] Lazy Loading of Heavy UI Components"; body="## [PROBLEM]`nLarge libraries like PDF previewers increase the initial bundle size significantly.`n`n## [REQUIRED FIX]`n- Implement `React.lazy` and `Suspense` for heavy components (e.g., `AnalysisDetail` view, PDF renderers).`n- Optimize chunking strategy in `vite.config.ts`."; label="critical,performance"},
    @{title="[Performance] Background OCR Processing via Worker Threads"; body="## [PROBLEM]`nPerforming OCR on large images blocks the main event loop, causing API unresponsive times.`n`n## [REQUIRED FIX]`n- Move `tesseract.js` processing to a background worker thread or a separate microservice.`n- Implement a polling/webhook mechanism to notify the frontend when OCR is complete."; label="critical,performance"},
    @{title="[Performance] Gzip/Brotli Compression for API Responses"; body="## [PROBLEM]`nLarge JSON payloads (e.g., tailored resumes) take longer to transfer over the network.`n`n## [REQUIRED FIX]`n- Add `compression` middleware to `app.ts`.`n- Configure it to support both Gzip and Brotli compression."; label="critical,performance"},
    @{title="[Infrastructure] Zero-Downtime Deployment Setup"; body="## [PROBLEM]`nDeployments currently cause brief service interruptions.`n`n## [REQUIRED FIX]`n- Update the deployment configuration to support blue-green or rolling updates.`n- Ensure database migrations are backward-compatible during the transition."; label="critical,infrastructure"},
    @{title="[Infrastructure] Centralized Logging with Pino + Logtail"; body="## [PROBLEM]`nLogs are currently only available in the local console, making production debugging difficult.`n`n## [REQUIRED FIX]`n- Update `lib/logger.ts` to stream logs to a centralized platform (e.g., Logtail or Sentry).`n- Implement structured logging for all API errors."; label="critical,infrastructure"},
    @{title="[Infrastructure] Secret Rotation Policy and Implementation"; body="## [PROBLEM]`nThere is no mechanism to rotate sensitive API keys (Paystack, Gemini) without downtime.`n`n## [REQUIRED FIX]`n- Implement a strategy for secret rotation using environment variable injection.`n- Document the manual or automated rotation process."; label="critical,infrastructure"},
    @{title="[Infrastructure] Dockerization for Consistent Environments"; body="## [PROBLEM]`nDifferences between local and production environments can lead to 'it works on my machine' bugs.`n`n## [REQUIRED FIX]`n- Create a multi-stage `Dockerfile` for the entire project.`n- Include a `docker-compose.yml` for local development with DB and Redis services."; label="critical,infrastructure"},
    @{title="[Compliance] GDPR 'Right to be Forgotten' Service"; body="## [PROBLEM]`nThere is no way to automatically handle user requests for data deletion.`n`n## [REQUIRED FIX]`n- Create a backend service that securely deletes all user records across all tables.`n- Implement a 'Delete Account' button in the Settings UI."; label="critical,compliance"},
    @{title="[Compliance] TOS Version Tracking and Re-acceptance"; body="## [PROBLEM]`nUpdating Terms of Service doesn't prompt existing users for re-acceptance.`n`n## [REQUIRED FIX]`n- Add a `tos_version` column to the `users` table.`n- Implement a modal that forces re-acceptance if the DB version is lower than the current app version."; label="critical,compliance"},
    @{title="[Features] Multi-Resume Comparison Matrix"; body="## [PROBLEM]`nUsers can only analyze one resume at a time against a job description.`n`n## [REQUIRED FIX]`n- Implement a 'Batch Analysis' feature.`n- Allow selecting multiple resumes and display a comparison matrix of match scores."; label="critical,feature"},
    @{title="[Features] AI-Driven Skills Gap Report"; body="## [PROBLEM]`nUsers only know what they are missing, but not how to fix it.`n`n## [REQUIRED FIX]`n- Update the AI prompt to include learning resources or certifications for 'Missing Skills'.`n- Display these as actionable links in the `AnalysisDetail` page."; label="critical,feature"},
    @{title="[Features] Export Tailored Resume to DOCX"; body="## [PROBLEM]`nSome users need Word documents instead of PDFs for further manual editing.`n`n## [REQUIRED FIX]`n- Implement a DOCX export endpoint using a library like `docx`.`n- Add a 'Download as Word' button to the results page."; label="critical,feature"},
    @{title="[Features] Collaborative Resume Review Mode"; body="## [PROBLEM]`nUsers cannot easily share their results with mentors for feedback.`n`n## [REQUIRED FIX]`n- Create a 'Shareable Link' feature with password protection.`n- Implement a simple commenting system for shared analyses."; label="critical,feature"},
    @{title="[Features] Advanced Parsing for Complex Resume Layouts"; body="## [PROBLEM]`nResumes with complex tables or multi-column layouts are often parsed incorrectly.`n`n## [REQUIRED FIX]`n- Improve the extraction logic in `resumes-extract.ts` to handle complex layouts.`n- Investigate using a more robust PDF parsing library or AI-assisted layout detection."; label="critical,feature"},
    @{title="[Features] Cover Letter Tone Customization"; body="## [PROBLEM]`nAI-generated cover letters are often too generic.`n`n## [REQUIRED FIX]`n- Add a 'Tone' selector (Professional, Creative, Bold) to the Analyze form.`n- Update the AI prompt to adjust its writing style based on this selection."; label="critical,feature"},
    @{title="[Features] LinkedIn Profile Optimization Generator"; body="## [PROBLEM]`nUsers have to manually translate their tailored resumes to LinkedIn.`n`n## [REQUIRED FIX]`n- Add a feature to generate LinkedIn 'About' and 'Experience' snippets.`n- Provide a 'Copy to Clipboard' button for each section."; label="critical,feature"},
    @{title="[Features] Multi-Language Resume Analysis Support"; body="## [PROBLEM]`nThe platform currently only reliably supports English.`n`n## [REQUIRED FIX]`n- Update the AI logic to detect and analyze resumes in Spanish, French, and German.`n- Ensure the frontend UI handles special characters correctly."; label="critical,feature"},
    @{title="[Features] Real-time Interview Prep Simulation"; body="## [PROBLEM]`Users are often unprepared for interviews even with a good resume.`n`n## [REQUIRED FIX]`n- Implement a chat-based interview simulator.`n- Use the generated 'Interview Questions' to conduct a mock interview via AI."; label="critical,feature"},
    @{title="[Security] Prevent Email Enumeration on Signup"; body="## [PROBLEM]`The signup endpoint reveals whether an email already exists, aiding account harvesting.`n`n## [REQUIRED FIX]`n- Update the signup route to return a generic 'Check your email' response regardless of email existence.`n- Implement rate limiting specifically for the signup endpoint."; label="critical,security"},
    @{title="[Security] Implementation of TOTP-Based MFA"; body="## [PROBLEM]`Accounts are only protected by single-factor authentication.`n`n## [REQUIRED FIX]`n- Add support for Time-based One-Time Passwords (TOTP) for Pro users.`n- Integrate a library like `otplib` and add a setup UI in Settings."; label="critical,security"},
    @{title="[Reliability] Request Timeout for AI API Calls"; body="## [PROBLEM]`Hanging AI API calls can exhaust server resources.`n`n## [REQUIRED FIX]`n- Set a strict 30-second timeout on all `axios` or `fetch` calls to OpenAI/Gemini.`n- Implement a retry logic for transient 503 errors."; label="critical,reliability"},
    @{title="[Reliability] React Error Boundaries for Dashboard Widgets"; body="## [PROBLEM]`A single JavaScript error in a widget can crash the entire dashboard UI.`n`n## [REQUIRED FIX]`n- Implement `ErrorBoundary` components around critical widgets (Stats, History list, Upload zone).`n- Show a 'Widget Unavailable' placeholder instead of a white screen."; label="critical,reliability"},
    @{title="[Performance] Static Asset Optimization via CDN"; body="## [PROBLEM]`Serving static assets directly from the API server increases latency.`n`n## [REQUIRED FIX]`n- Configure a CDN (e.g., Cloudflare) for all public assets.`n- Update build scripts to use fingerprinting for aggressive caching."; label="critical,performance"},
    @{title="[Performance] SQL Join Optimization for Dashboard Stats"; body="## [PROBLEM]`Fetching dashboard data requires multiple separate queries.`n`n## [REQUIRED FIX]`n- Combine data fetching into a single optimized SQL join.`n- Use Drizzle's relational query API to reduce overhead."; label="critical,performance"},
    @{title="[Infrastructure] Health and Readiness Endpoints"; body="## [PROBLEM]`Monitoring tools cannot easily check the health of the application.`n`n## [REQUIRED FIX]`n- Add `/health` (liveness) and `/ready` (readiness) endpoints.`n- The readiness check should verify DB and Redis connectivity."; label="critical,infrastructure"},
    @{title="[Infrastructure] Automated Accessibility (A11y) Testing"; body="## [PROBLEM]`New UI changes could accidentally introduce accessibility barriers.`n`n## [REQUIRED FIX]`n- Integrate `axe-core` or a similar tool into the CI pipeline.`n- Fail builds that introduce critical accessibility violations."; label="critical,infrastructure"},
    @{title="[Compliance] Full Data Portability (JSON Export)"; body="## [PROBLEM]`Users cannot easily migrate their data out of the platform.`n`n## [REQUIRED FIX]`n- Implement a 'Download All My Data' feature in Settings.`n- Export all resumes, analyses, and profile data in a structured JSON format."; label="critical,compliance"},
    @{title="[Compliance] Secure Document Purgatory (S3 cleanup)"; body="## [PROBLEM]`Deleting a resume from the DB might leave orphaned files in storage.`n`n## [REQUIRED FIX]`n- Implement a lifecycle policy or a hook to ensure storage files are deleted when DB records are removed.`n- Add a 'secure purge' log for auditing."; label="critical,compliance"}
)

Write-Host "Creating 40 NEW critical issues..."
foreach ($issue in $newIssues) {
    gh issue create --title $issue.title --body $issue.body --label $issue.label
}

Write-Host "All tasks completed!"
