$repo = "chigozirim007/resume-ai-platform"

$issues = @(
  @{ title="[Testing] Zero unit tests across the entire monorepo — no test runner configured"; label="critical"; body="There are no test files, no jest/vitest config, and no test script in any package.json. The codebase has zero automated test coverage.`n`n**Fix:** Configure Vitest for the frontend and Jest/Supertest for the API server. Add a test script to the root package.json." }
  @{ title="[Testing] No integration tests for any API endpoint"; label="critical"; body="No endpoint has a test. Core flows like POST /api/analyses, the Paystack webhook, and auth sync are completely untested.`n`n**Fix:** Add Supertest-based integration tests for all critical routes." }
  @{ title="[Testing] No E2E tests for the core analysis workflow"; label="enhancement"; body="The full user journey (signup → upload resume → analyze → view results → download PDF) has no automated E2E coverage.`n`n**Fix:** Add Playwright or Cypress E2E tests for the critical user flow." }
  @{ title="[Testing] No test for free plan enforcement — limit can be silently broken by code changes"; label="critical"; body="The 3-analysis free limit logic has no test. Any refactor could disable it without detection.`n`n**Fix:** Add a test that verifies the 4th analysis attempt returns HTTP 403 for free plan users." }
  @{ title="[Testing] No test for Paystack webhook signature validation"; label="critical"; body="The validateWebhookSignature() function is never tested. A bug could allow unsigned webhooks to upgrade arbitrary users to Pro.`n`n**Fix:** Add unit tests for valid and invalid signatures." }
  @{ title="[Testing] No test for the AI response JSON parser in ai.ts"; label="critical"; body="The JSON.parse(content) in analyzeResume() has no test. Truncated OpenAI responses (at max_tokens) produce invalid JSON that would crash the server.`n`n**Fix:** Add unit tests for the parser with mocked responses including truncated/malformed JSON." }
  @{ title="[Testing] No test for PDF/DOCX/image text extraction pipeline"; label="enhancement"; body="The resumes/extract endpoint handles PDF, DOCX, and OCR image paths. None are tested.`n`n**Fix:** Add integration tests using fixture files for each supported format." }
  @{ title="[Testing] No snapshot tests for any UI components"; label="enhancement"; body="No component has a snapshot or visual regression test. UI regressions go undetected.`n`n**Fix:** Add Vitest + Testing Library snapshot tests for key components." }
  @{ title="[Testing] No test for the LCS diff algorithm in analysis-detail.tsx"; label="enhancement"; body="The computeDiff() function is a custom LCS implementation. It has no unit tests. Edge cases (empty strings, identical content, very long lines) are untested.`n`n**Fix:** Extract computeDiff to a utility file and add unit tests." }
  @{ title="[Testing] No test for the job scraper Cheerio selector logic"; label="enhancement"; body="The scrape-job endpoint tries multiple CSS selectors to find job description text. The fallback logic has no tests.`n`n**Fix:** Add unit tests mocking axios and testing each selector priority." }
  @{ title="[DevOps] No .env.example file — contributors cannot know which environment variables are required"; label="critical"; body="There is no .env.example in the repository. Contributors must read source code to find all required env vars (DATABASE_URL, SUPABASE_JWT_SECRET, PAYSTACK_SECRET_KEY, etc.).`n`n**Fix:** Create a .env.example listing all required and optional variables with descriptions." }
  @{ title="[DevOps] No GitHub Actions CI pipeline — PRs are merged with no automated checks"; label="critical"; body="There is no .github/workflows/ directory. No CI runs on pull requests.`n`n**Fix:** Add a CI workflow that runs lint, type-check, and tests on every PR." }
  @{ title="[DevOps] No GitHub Actions CD pipeline — deployments are entirely manual"; label="enhancement"; body="Deployments are done manually via Replit. There is no automated deploy on merge to main.`n`n**Fix:** Add a CD workflow that deploys on push to main." }
  @{ title="[DevOps] drizzle-kit push used in production — schema changes cannot be rolled back"; label="critical"; body="The DB setup uses drizzle-kit push which applies schema changes directly with no migration files. If a bad change is pushed, there is no rollback path.`n`n**Fix:** Switch to drizzle-kit generate + migrate and commit migration files to the repo." }
  @{ title="[DevOps] /api/healthz returns ok without checking DB connectivity"; label="enhancement"; body="The health check endpoint returns { status: 'ok' } unconditionally. If the DB is down, the health check still passes.`n`n**Fix:** Execute a simple SELECT 1 query and return 503 if it fails." }
  @{ title="[DevOps] No graceful shutdown handler — in-flight requests are killed on SIGTERM"; label="enhancement"; body="The server has no process.on('SIGTERM') handler. Running requests are dropped on deployment restarts.`n`n**Fix:** Add a graceful shutdown that stops accepting new requests and waits for existing ones to finish." }
  @{ title="[DevOps] No startup validation of required env vars — missing DATABASE_URL causes a cryptic runtime crash"; label="enhancement"; body="If DATABASE_URL is missing, the app crashes with an obscure pg connection error at the first DB call, not at startup.`n`n**Fix:** Add a startup check using zod or a custom validator that lists all missing required env vars and exits clearly." }
  @{ title="[DevOps] package-lock.json present in repo root alongside pnpm-lock.yaml — dual package manager conflict"; label="bug"; body="Having both package-lock.json (npm) and pnpm-lock.yaml (pnpm) in the same repo confuses contributors and CI tools.`n`n**Fix:** Delete package-lock.json and add it to .gitignore. Enforce pnpm via engines field." }
  @{ title="[DevOps] No Renovate or Dependabot configured — security patches for dependencies are not automated"; label="enhancement"; body="No automated dependency update bot is configured. Security vulnerabilities in dependencies will go unpatched until manually noticed.`n`n**Fix:** Add a Renovate or Dependabot config." }
  @{ title="[DevOps] No pino-pretty in development — JSON logs are unreadable without external tooling"; label="enhancement"; body="Pino outputs JSON log lines in development, which are difficult to read in a terminal.`n`n**Fix:** Add pino-pretty as a dev dependency and configure the logger to use it when NODE_ENV=development." }
  @{ title="[Accessibility] Animated blobs on login/signup have no prefers-reduced-motion check"; label="enhancement"; body="The Framer Motion infinite animations on login/signup pages will play regardless of the user's prefers-reduced-motion OS setting, causing issues for users with vestibular disorders.`n`n**Fix:** Wrap animation props in a useReducedMotion() check and disable animations when true." }
  @{ title="[Accessibility] Delete button on analysis-detail is icon-only with no aria-label"; label="critical"; body="The Trash2 icon button has no aria-label or title. Screen readers announce it as an unlabeled button.`n`n**Fix:** Add aria-label='Delete analysis' to the button." }
  @{ title="[Accessibility] Score Meter SVG has no accessible text — screen readers cannot read the score"; label="critical"; body="The circular SVG progress meter in analysis-detail.tsx has no <title>, aria-label, or role='img' attribute.`n`n**Fix:** Add role='img' and aria-label={Score ${score} out of 100} to the SVG." }
  @{ title="[Accessibility] Login/signup inputs missing autocomplete attributes — password managers cannot autofill"; label="enhancement"; body="The email and password inputs don't have autocomplete='email', autocomplete='current-password', or autocomplete='new-password'. Password managers and browser autofill are impaired.`n`n**Fix:** Add appropriate autocomplete attributes to all auth form inputs." }
  @{ title="[Accessibility] Matched vs missing keywords distinguished by color only — fails WCAG 1.4.1"; label="critical"; body="Keywords are shown as green (matched) or red (missing) chips. Users with red/green color blindness cannot distinguish them.`n`n**Fix:** Add an icon (CheckCircle/XCircle) or text label ('matched'/'missing') to each chip in addition to color." }
  @{ title="[Docs] CONTRIBUTING.md has no local dev setup instructions — new contributors are blocked"; label="critical"; body="CONTRIBUTING.md links to GitHub Issues but doesn't explain how to run the project locally (PostgreSQL setup, Supabase config, Paystack test keys, pnpm commands).`n`n**Fix:** Add a detailed Local Development section to CONTRIBUTING.md." }
  @{ title="[Docs] No Swagger/ReDoc UI served from the API — OpenAPI spec is not accessible to developers"; label="enhancement"; body="The openapi.yaml file exists but is not served as an interactive UI. Developers must read raw YAML.`n`n**Fix:** Serve swagger-ui-express or redoc at /api/docs." }
  @{ title="[Docs] mockup-sandbox package has no README — its purpose is undocumented"; label="enhancement"; body="The artifacts/mockup-sandbox directory exists with no README explaining what it's for, how to run it, or how it relates to the rest of the project.`n`n**Fix:** Add a README.md to mockup-sandbox." }
  @{ title="[Docs] replit.md is Replit-specific — no instructions for self-hosted or local deployment"; label="enhancement"; body="replit.md explains how to run on Replit but there are no instructions for developers who want to run the project locally or on a VPS.`n`n**Fix:** Add a Local Development / Self-Hosting section to the main README." }
  @{ title="[Docs] No CHANGELOG.md — users and contributors cannot track changes between versions"; label="enhancement"; body="There is no changelog. Contributors cannot see what changed recently or in past releases.`n`n**Fix:** Add a CHANGELOG.md following Keep a Changelog format, and update it with each release." }
  @{ title="[Bug] analyses.ts POST response includes raw interviewQuestions JSON string — client receives string not array"; label="bug"; body="In POST /api/analyses, the response object spreads finalAnalysis (which has interviewQuestions as a JSON string) but does not parse it. Clients receive a string instead of an array.`n`n**Fix:** Parse interviewQuestions before including it in the response, same as keywordsMatched/keywordsMissing." }
  @{ title="[Bug] GET /api/analyses response includes raw interviewQuestions JSON string — not parsed like keywords"; label="bug"; body="In GET /api/analyses, keywordsMatched and keywordsMissing are parsed but interviewQuestions is not. The client receives a raw JSON string for interviewQuestions.`n`n**Fix:** Add JSON.parse for interviewQuestions in the map() function." }
  @{ title="[Bug] GET /api/analyses/:id response also returns interviewQuestions as raw JSON string"; label="bug"; body="Same interviewQuestions parsing bug in the single-analysis GET endpoint. The field is not parsed before sending.`n`n**Fix:** Parse interviewQuestions in the single-analysis response, consistent with keyword fields." }
  @{ title="[Bug] analysesTable matchScore default is 0 — 'analyzing' status records pollute average score calculation"; label="bug"; body="GET /dashboard/stats uses avg(matchScore) which includes 'analyzing' records with matchScore=0, skewing the average downward.`n`n**Fix:** Filter WHERE status = 'completed' in the avg() query." }
  @{ title="[Security] No file upload rate limiting — users can spam PDF extraction endpoint to exhaust server CPU"; label="critical"; body="The aiRateLimiter on /resumes/extract is the only protection. There is no per-user daily limit on extraction requests. Tesseract OCR is CPU-intensive.`n`n**Fix:** Add a per-user rate limit specifically for the extraction endpoint." }
  @{ title="[Security] Paystack webhook responds 200 even on DB errors — Paystack won't retry, events lost silently"; label="critical"; body="The webhook handler catches DB errors and still returns res.sendStatus(200). Paystack considers the event delivered and won't retry. Plan upgrades triggered by the webhook can be silently lost.`n`n**Fix:** Return 500 on DB errors so Paystack retries the webhook." }
  @{ title="[Bug] Settings page has no 'Change Password' functionality for email/password users"; label="bug"; body="Users who signed up with email/password have no way to change their password from within the app.`n`n**Fix:** Add a Change Password form in Settings that calls supabase.auth.updateUser({ password: newPassword })." }
  @{ title="[Bug] Profile image URL is never updated after initial Supabase sync — Google OAuth avatar changes are not reflected"; label="bug"; body="The authMiddleware and auth/user endpoint upsert profileImageUrl from the JWT, but if a user changes their Google avatar, it won't be updated until they log out and back in. The onConflictDoUpdate in auth.ts should handle this but only fires on sync, not on JWT refresh.`n`n**Fix:** Ensure every authenticated request updates profileImageUrl from the current JWT claims." }
  @{ title="[Performance] Landing page review section has no stale-while-revalidate — always fetches fresh on every load"; label="enhancement"; body="useListReviews on the landing page refetches on every mount with no staleTime configured. The reviews rarely change but are fetched on every landing page visit.`n`n**Fix:** Set staleTime: 5 * 60 * 1000 on the reviews query." }
  @{ title="[Performance] No virtual scrolling on History page — all analysis cards rendered in DOM at once"; label="enhancement"; body="The history page renders every analysis card in the DOM simultaneously. With hundreds of analyses, this causes significant layout thrashing.`n`n**Fix:** Use pagination (preferred) or a virtual list library like @tanstack/react-virtual." }
  @{ title="[Bug] PDF export via pdfkit uses Helvetica font — non-Latin characters (CJK, Arabic) render as blank boxes"; label="bug"; body="The server-side PDF export in analyses.ts uses PDFDocument with the default Helvetica font, which does not include non-Latin glyphs. Resumes with Arabic or Chinese text will have missing characters in the export.`n`n**Fix:** Embed a Unicode-supporting font (e.g. Noto Sans) in the PDF export." }
  @{ title="[Bug] PDF export endpoint does not set Content-Length header — download progress bar never shows"; label="enhancement"; body="The streaming PDF response from GET /analyses/:id/export has no Content-Length, so the browser cannot show a progress bar.`n`n**Fix:** Generate the PDF to a buffer first, set Content-Length, then send the buffer." }
  @{ title="[Bug] analyzeResume has no request timeout — a hung OpenAI connection blocks the Express thread indefinitely"; label="critical"; body="If OpenAI's API hangs (no response), the POST /api/analyses handler waits forever, holding the server connection open.`n`n**Fix:** Add AbortSignal.timeout() or a Promise.race with a timeout of 60s to the OpenAI call." }
  @{ title="[Bug] 'analyzing' status records are never cleaned up if the server crashes mid-analysis"; label="bug"; body="If the server crashes after inserting the 'analyzing' record but before the AI responds, the record stays in 'analyzing' state permanently and appears in the user's history.`n`n**Fix:** Add a startup job that resets any records stuck in 'analyzing' for more than 5 minutes to a 'failed' status." }
  @{ title="[Bug] No error boundary in analysis-detail.tsx — any runtime error shows a blank page with no recovery"; label="bug"; body="If the analysis-detail page throws during render (e.g. malformed data from the API), the entire page goes blank with no error message or back button.`n`n**Fix:** Wrap the page in a React Error Boundary that shows a meaningful error state." }
  @{ title="[UX] No avatar/profile picture upload in Settings — users cannot personalize their account"; label="enhancement"; body="The Settings page allows editing first/last name but has no avatar upload. Supabase Storage supports file uploads.`n`n**Fix:** Add an avatar upload input in Settings that uploads to Supabase Storage and updates the profileImageUrl." }
  @{ title="[UX] Score meter ring animates on every re-render, not just on initial load"; label="bug"; body="The SVG stroke-dashoffset transition fires whenever the component re-renders, not just on mount. This causes the ring to re-animate unexpectedly.`n`n**Fix:** Use a CSS animation triggered by a mount class or initialize strokeDashoffset to the final value immediately." }
  @{ title="[UX] Analyze page submit button is disabled until all 3 fields filled — no inline validation messaging"; label="enhancement"; body="The submit button is disabled with a generic message. There is no per-field validation feedback (e.g. 'Job title is required' under the input).`n`n**Fix:** Add inline validation messages using react-hook-form or manual state." }
  @{ title="[UX] No 'Save to My Resumes' action after analysis — tailored resume cannot be saved directly to the library"; label="enhancement"; body="After viewing a tailored resume in analysis-detail, users have no way to save it to their resume library directly. They must copy-paste it manually.`n`n**Fix:** Add a 'Save as Resume' button that calls POST /api/resumes with the tailored resume content." }
  @{ title="[UX] No email notification when analysis is complete — users must keep the tab open"; label="enhancement"; body="Analysis takes 15-30 seconds. Users who navigate away miss the result. There is no notification mechanism.`n`n**Fix:** Implement an email notification via Supabase's email service or Resend when analysis status changes to 'completed'." }
)

$created = 0
foreach ($issue in $issues) {
  Write-Host "Creating: $($issue.title)"
  gh issue create --repo $repo --title $issue.title --body $issue.body --label $issue.label 2>&1
  $created++
  Start-Sleep -Milliseconds 500
}
Write-Host "Done. Created $created issues."
