$repo = "chigozirim007/resume-ai-platform"

$issues = @(
  @{ title="[Bug] DELETE /api/analyses/:id missing ownership check — any user can delete any analysis"; label="critical"; body="In routes/analyses.ts, DELETE /analyses/:id deletes by ID without checking analysis.userId === req.user.id. Any authenticated user can delete any analysis by guessing the serial integer ID.`n`n**Fix:** Add ownership check before delete, return 403 if mismatch." }
  @{ title="[Bug] PATCH /api/resumes/:id missing ownership check — any user can overwrite any resume"; label="critical"; body="In routes/resumes.ts, PATCH /resumes/:id updates the row without verifying ownership before the update query runs. The check happens AFTER the update (checking the returned row), meaning the write already occurred.`n`n**Fix:** Add a SELECT ownership check before the UPDATE." }
  @{ title="[Bug] DELETE /api/resumes/:id missing ownership check — any user can delete any resume"; label="critical"; body="Similar to the analyses delete issue. The delete runs without verifying resume.userId === req.user.id before executing.`n`n**Fix:** Add pre-delete ownership check." }
  @{ title="[Security] GET /api/paystack/verify — reference not bound to authenticated user, enables account upgrade hijack"; label="critical"; body="GET /paystack/verify?reference=xxx upgrades req.user.id to Pro if the reference is successful. A user who obtains another user's payment reference can use it to upgrade their own account instead.`n`n**Fix:** Validate that the transaction metadata.userId matches req.user.id." }
  @{ title="[Bug] Free plan limit check happens AFTER inserting 'analyzing' record — orphaned ghost records created"; label="bug"; body="In POST /api/analyses, the 'analyzing' record is inserted BEFORE the plan limit check. When the limit is exceeded (HTTP 403), the ghost record remains in the DB with status='analyzing' forever.`n`n**Fix:** Move the plan limit check before any DB inserts." }
  @{ title="[Bug] JSON.parse in ai.ts has no try/catch — malformed OpenAI response causes unhandled 500"; label="bug"; body="In lib/ai.ts line 78: JSON.parse(content) is not wrapped in try/catch. If OpenAI returns malformed JSON (which happens when max_tokens is hit mid-response), the server throws an unhandled error.`n`n**Fix:** Wrap in try/catch and return a descriptive error." }
  @{ title="[Bug] AuthGate calls login() inside setTimeout during render — race condition causes multiple redirects"; label="bug"; body="In App.tsx, when !isAuthenticated, login() is called via setTimeout(0). If the component re-renders before the timeout fires, multiple login() calls can be queued.`n`n**Fix:** Use a ref flag or useEffect to ensure login() is called only once." }
  @{ title="[Bug] 'Forgot Password' link on login page is href='#' — completely non-functional"; label="bug"; body="In pages/login.tsx, the forgot password anchor has href='#'. Clicking it does nothing. Users with forgotten passwords have no recovery path.`n`n**Fix:** Implement forgot password flow using supabase.auth.resetPasswordForEmail()." }
  @{ title="[Bug] checkout-success.tsx shows success without verifying payment — failed payments display success screen"; label="bug"; body="pages/checkout-success.tsx renders a success message without calling GET /api/paystack/verify. A user who navigates directly to /checkout/success sees a false confirmation.`n`n**Fix:** Call /api/paystack/verify on mount and conditionally render success/failure." }
  @{ title="[Bug] Re-analyze passes resumeContent as URL query param — breaks for resumes over ~2KB (URL length limit)"; label="bug"; body="In analysis-detail.tsx, handleReAnalyze() encodes full resumeContent into URLSearchParams. Browsers enforce ~2048 char URL limits. Long resumes silently truncate.`n`n**Fix:** Use sessionStorage or a shared state store instead of URL params for large content." }
  @{ title="[UX] Mobile sidebar does not close after navigation — user must manually dismiss it"; label="enhancement"; body="After tapping a nav item on mobile, the sidebar remains open, obscuring the page content.`n`n**Fix:** Call the sidebar close function (from SidebarProvider context) in the Link onClick handler." }
  @{ title="[UX] No loading skeleton on Resumes page while data is fetching"; label="enhancement"; body="The /resumes page shows a blank area while the resume list loads. There is no skeleton or spinner.`n`n**Fix:** Add Skeleton components matching the resume card layout." }
  @{ title="[UX] Empty dashboard has no onboarding CTA for brand-new users with 0 analyses and 0 resumes"; label="enhancement"; body="New users land on /dashboard and see zero-state stats with no guidance. There is no 'Start your first analysis' prompt.`n`n**Fix:** Add an onboarding empty state card linking to /analyze." }
  @{ title="[UX] 'Suggested Answer Tips' button on Interview Prep tab is a non-functional placeholder"; label="bug"; body="In analysis-detail.tsx, each interview question has a 'Suggested Answer Tips' Button with no onClick handler. It does nothing.`n`n**Fix:** Either implement the feature or remove the button." }
  @{ title="[UX] No confirmation dialog before deleting an analysis or resume — accidental data loss"; label="enhancement"; body="The delete buttons on analysis-detail and resumes pages execute immediately on click with no confirmation prompt.`n`n**Fix:** Add an AlertDialog confirmation step before executing deletes." }
  @{ title="[UX] History page has no pagination — all analyses load at once, causing performance issues"; label="enhancement"; body="GET /api/analyses returns all records. The history page renders every card at once. For users with hundreds of analyses this is very slow.`n`n**Fix:** Implement cursor-based or offset pagination on the API and infinite scroll or page controls on the frontend." }
  @{ title="[UX] History page has no search or filter by job title, company, or score"; label="enhancement"; body="Users cannot find a specific past analysis without scrolling through the entire list.`n`n**Fix:** Add a search input that filters analyses by jobTitle/companyName, and a score range filter." }
  @{ title="[UX] Analysis date displayed without timezone — shows different dates for users in different timezones"; label="bug"; body="analysis-detail.tsx uses new Date(analysis.createdAt).toLocaleDateString() which varies by user locale and timezone. The stored timestamp is UTC.`n`n**Fix:** Use a consistent display format with explicit timezone (e.g. 'en-GB' with timeZone: 'UTC')." }
  @{ title="[Bug] Copy to clipboard fails silently on non-HTTPS origins — no error feedback to user"; label="bug"; body="navigator.clipboard.writeText() is only available in secure contexts (HTTPS or localhost). On plain HTTP it throws, but the CopyButton component has no catch handler.`n`n**Fix:** Add try/catch and fall back to document.execCommand('copy') with a user-facing error toast." }
  @{ title="[Security] SSRF via /api/scrape/job — no URL allowlist blocks requests to internal network addresses"; label="critical"; body="POST /api/scrape/job accepts any URL and makes a server-side HTTP request. An attacker can target 169.254.169.254 (cloud metadata), localhost, or internal services.`n`n**Fix:** Validate the URL resolves to a public IP; block RFC 1918, loopback, and link-local ranges." }
  @{ title="[Security] CORS configured with origin:true — any origin can make credentialed requests in production"; label="critical"; body="In app.ts: cors({ credentials: true, origin: true }). This reflects any Origin header, allowing any domain to make authenticated API calls.`n`n**Fix:** Set origin to an explicit allowlist of trusted frontend domains." }
  @{ title="[Security] No file size limit on /api/resumes/extract — server can be DoS'd with large uploads"; label="critical"; body="The multer config uses memoryStorage() with no limits option. An attacker can upload a multi-GB file, exhausting server RAM.`n`n**Fix:** Add limits: { fileSize: 10 * 1024 * 1024 } to the multer config." }
  @{ title="[Security] MIME type not validated against file signature — file type can be spoofed via Content-Type header"; label="critical"; body="resumes-extract.ts branches on req.file.mimetype which comes from the client's Content-Type. A malicious file can have mimetype='application/pdf' while containing arbitrary data.`n`n**Fix:** Use a magic-bytes library (e.g. file-type) to verify the actual file signature." }
  @{ title="[Security] In-memory rate limiter resets on server restart — DoS protection is ephemeral"; label="critical"; body="The rate limiter (api-server/src/middlewares/rate-limiter.ts) uses an in-memory store. Every server restart clears all counters, allowing burst attacks after restarts.`n`n**Fix:** Back the rate limiter with Redis or a persistent store." }
  @{ title="[Security] No CSRF protection on any state-changing API endpoint"; label="critical"; body="POST /api/analyses, POST /api/resumes, DELETE /api/analyses/:id etc. rely on Bearer tokens but cookies (sid) are also sent. If cookie auth is used, CSRF is possible.`n`n**Fix:** Add a CSRF token validation layer or use SameSite=Strict cookies." }
  @{ title="[Security] Paystack charge.success userId metadata is not validated — can be forged in Paystack test mode"; label="critical"; body="In paystack webhook handler, the userId is taken directly from event.data.metadata.userId. In Paystack test mode, anyone can trigger a charge.success with a forged userId to upgrade arbitrary accounts.`n`n**Fix:** Cross-reference the Paystack customer_code against paystackCustomerCode in the DB rather than trusting metadata." }
  @{ title="[Security] /api/scrape/job is unauthenticated — acts as an open proxy for anyone on the internet"; label="critical"; body="POST /api/scrape/job has no req.isAuthenticated() check. Any unauthenticated actor can use it as a free server-side HTTP proxy.`n`n**Fix:** Add authentication check at the top of the scrape handler." }
  @{ title="[Security] No audit log for sensitive operations — plan upgrades, deletions, and auth events are not recorded"; label="enhancement"; body="There is no audit trail for when a user is upgraded to Pro, when analyses are deleted, or when auth events occur. This makes incident response and fraud detection impossible.`n`n**Fix:** Implement an audit_log table and record sensitive operations." }
  @{ title="[Security] No account deletion flow — GDPR Article 17 right to erasure not implemented"; label="critical"; body="Users have no way to delete their account and associated data from within the app. This is required under GDPR Article 17.`n`n**Fix:** Add account deletion in Settings that removes all user data from PostgreSQL and Supabase Auth." }
  @{ title="[Performance] GET /api/analyses returns full jobDescription and resumeContent in list view — huge payload"; label="enhancement"; body="The analyses list endpoint returns every field including large text blobs. For a user with 100 analyses, this payload can be several MB.`n`n**Fix:** Return a summary projection (id, jobTitle, companyName, matchScore, status, createdAt) for list views." }
  @{ title="[Performance] No DB index on analyses.user_id — every history query does a full table scan"; label="enhancement"; body="The analyses table has no index on user_id. Every call to GET /api/analyses does a sequential scan of the entire table.`n`n**Fix:** Add CREATE INDEX idx_analyses_user_id ON analyses(user_id)." }
  @{ title="[Performance] No DB index on resumes.user_id — resume list query does full table scan"; label="enhancement"; body="Same issue as analyses.user_id — the resumes table has no index on user_id.`n`n**Fix:** Add CREATE INDEX idx_resumes_user_id ON resumes(user_id)." }
  @{ title="[Performance] No DB index on analyses.created_at — ORDER BY created_at is a full sort on every request"; label="enhancement"; body="Dashboard and history queries ORDER BY created_at DESC with no supporting index.`n`n**Fix:** Add CREATE INDEX idx_analyses_created_at ON analyses(user_id, created_at DESC)." }
  @{ title="[Performance] computeDiff LCS algorithm in analysis-detail.tsx is O(m*n) — freezes browser for long resumes"; label="bug"; body="The diff view builds a full m*n DP matrix in the browser's main thread. For a 500-line resume, this is 250,000 operations synchronously, blocking the UI.`n`n**Fix:** Run the diff in a Web Worker or use a windowed/chunk approach." }
  @{ title="[Performance] GET /dashboard/recent-analyses accepts unbounded limit param — can request millions of rows"; label="critical"; body="The limit query param has no maximum. A request with ?limit=999999999 will attempt to fetch millions of rows.`n`n**Fix:** Cap limit at a maximum of 50 and validate it is a positive integer." }
  @{ title="[Data] keywordsMatched and keywordsMissing stored as TEXT JSON strings instead of JSONB"; label="enhancement"; body="These columns are defined as text() in the Drizzle schema but contain JSON arrays. Using JSONB enables native array queries, indexing, and avoids manual JSON.parse/stringify on every read/write.`n`n**Fix:** Migrate columns to jsonb type." }
  @{ title="[Data] interviewQuestions stored as TEXT JSON string instead of JSONB"; label="enhancement"; body="Same issue as keywords columns — interviewQuestions is text() containing a JSON array.`n`n**Fix:** Migrate to jsonb." }
  @{ title="[Data] analyses.resume_id has no FK constraint to resumes table — referential integrity not enforced"; label="bug"; body="In the analyses schema, resumeId is defined as integer('resume_id') without a .references() call. Deleting a resume leaves dangling resume_id values in analyses.`n`n**Fix:** Add .references(() => resumesTable.id, { onDelete: 'set null' })." }
  @{ title="[Data] usersTable.passwordHash column is never written or read — dead schema weight"; label="enhancement"; body="The users schema defines passwordHash but it is never set anywhere in the codebase (Supabase handles auth). This is unused columns adding confusion.`n`n**Fix:** Remove the column and create a migration." }
  @{ title="[Data] No ON DELETE CASCADE on analyses.user_id — orphaned analyses if user record is deleted"; label="bug"; body="If a user row is deleted from the users table, their analyses remain with a broken FK reference.`n`n**Fix:** Add onDelete: 'cascade' to the analyses userId FK reference." }
  @{ title="[Data] No ON DELETE CASCADE on resumes.user_id — orphaned resumes if user is deleted"; label="bug"; body="Same as the analyses cascade issue for the resumes table.`n`n**Fix:** Add onDelete: 'cascade' to the resumes userId FK." }
  @{ title="[Data] analyses.matchScore defaults to 0 — 'analyzing' records show as 0% match in history"; label="bug"; body="While an analysis is in-progress (status='analyzing'), matchScore=0. If the history page is open during processing, it shows 0% incorrectly.`n`n**Fix:** Filter out 'analyzing' status from list views, or use null as the default for matchScore." }
  @{ title="[API] GET /api/resumes has no pagination — returns all resumes, will break at scale"; label="enhancement"; body="The resumes endpoint returns all rows for a user with no limit or cursor.`n`n**Fix:** Add limit/offset or cursor-based pagination." }
  @{ title="[API] GET /api/analyses has no pagination — full analysis history returned on every request"; label="enhancement"; body="The analyses list endpoint has no pagination. Add limit/offset with a default of 20." }
  @{ title="[API] API error responses are inconsistent — some endpoints return {error:string}, others vary"; label="enhancement"; body="Some endpoints return { error: 'message' }, others throw unhandled errors that Express formats differently. This makes client-side error handling unreliable.`n`n**Fix:** Standardize all error responses to { error: string, code?: string }." }
  @{ title="[API] No ETag or Cache-Control headers on GET endpoints — clients cannot cache responses"; label="enhancement"; body="None of the GET endpoints set ETag, Last-Modified, or Cache-Control headers. Browsers re-fetch on every navigation.`n`n**Fix:** Add ETag support to analysis and resume endpoints." }
  @{ title="[API] Missing interviewQuestions field in Analysis OpenAPI schema definition"; label="bug"; body="The Analysis schema in openapi.yaml does not include the interviewQuestions field in its required or properties list, even though the API always returns it.`n`n**Fix:** Add interviewQuestions to the Analysis schema." }
  @{ title="[Auth] Supabase access token never refreshed client-side — sessions silently expire after 1 hour"; label="critical"; body="The replit-auth-web library stores the initial Supabase session but may not call supabase.auth.onAuthStateChange to auto-refresh tokens. After 1 hour, API calls start returning 401.`n`n**Fix:** Ensure onAuthStateChange is wired up to refresh the session and update the auth context." }
  @{ title="[Auth] Google OAuth users synced to local DB only via authMiddleware — race condition on first request"; label="bug"; body="Google OAuth redirects to /dashboard, which immediately fetches /api/auth/user. The authMiddleware auto-upsert may race with the first dashboard data request if both fire simultaneously.`n`n**Fix:** Ensure the OAuth callback explicitly calls POST /api/auth/sync before redirecting." }
  @{ title="[Auth] No session invalidation on logout — JWT remains valid until natural expiry"; label="critical"; body="Logging out via supabase.auth.signOut() clears the local token but the JWT itself remains valid on the server for up to 1 hour. There is no token blacklist.`n`n**Fix:** Implement a server-side token revocation list or use short-lived access tokens with refresh token rotation." }
)

$created = 0
foreach ($issue in $issues) {
  Write-Host "Creating: $($issue.title)"
  gh issue create --repo $repo --title $issue.title --body $issue.body --label $issue.label 2>&1
  $created++
  Start-Sleep -Milliseconds 500
}
Write-Host "Done. Created $created issues."
